version: '3'
services:
  db:
    container_name: DBDaniel
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hades2021+
      MYSQL_DATABASE: mitiendaDaniel
      MYSQL_USER: rubianoDaniel
      MYSQL_PASSWORD: Hades2021+
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
